modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="elijah"
version="${mod_version}"
displayName="Elijah Pirate"
authors="jamesrenrold-lab"
description='''Pirate Origin: a dedicated nine-gunpowder pouch, recoil-driven flintlock, dirty tactics and a short-lived undead crew.'''

[[dependencies.elijah]]
modId="forge"
mandatory=true
versionRange="[47.4.4,48)"
ordering="NONE"
side="BOTH"

[[dependencies.elijah]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
